# Generated by Django 4.0.3 on 2022-03-20 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], default='P', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lecture_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lecturescheduler')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
